/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./saturn.glb --transform 
Files: ./saturn.glb [5.48MB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/saturn-transformed.glb [23.15KB] (100%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

function Saturn({ diameter }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/saturn-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh geometry={nodes.Saturn001.geometry} material={materials.None} />
      <mesh
        geometry={nodes.RingsTop.geometry}
        material={materials.SaturnRings}
      />
    </group>
  );
}

export default Saturn;

useGLTF.preload("/models/saturn-transformed.glb");
