/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./asteroid-itokawa.glb --transform 
Files: ./asteroid-itokawa.glb [1.69MB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/asteroid-itokawa-transformed.glb [116.16KB] (93%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

const Asteroid = ({ diameter }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/asteroid-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh geometry={nodes.itokawa_LP.geometry} material={materials.itokawa} />
    </group>
  );
};

export default Asteroid;

useGLTF.preload("/models/asteroid-transformed.glb");
