/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./earth.glb --transform 
Files: ./earth.glb [12.92MB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/earth-transformed.glb [113.48KB] (99%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

function Earth({ diameter }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/earth-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Default OBJ"]}
      />
    </group>
  );
}

export default Earth;

useGLTF.preload("/models/earth-transformed.glb");
