/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./jupiter.glb --transform 
Files: ./jupiter.glb [11.48MB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/jupiter-transformed.glb [45.27KB] (100%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

const Jupiter = ({ diameter }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/jupiter-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh geometry={nodes.cubemap.geometry} material={materials.None} />
    </group>
  );
};

export default Jupiter;

useGLTF.preload("/models/jupiter-transformed.glb");
