/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./mercury.glb --transform 
Files: ./mercury.glb [3.05MB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/mercury-transformed.glb [98.62KB] (97%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

function Mercury({ diameter }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/mercury-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Default OBJ.005"]}
      />
    </group>
  );
}

export default Mercury;

useGLTF.preload("/models/mercury-transformed.glb");
