/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./neptune.glb --transform 
Files: ./neptune.glb [585.1KB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/neptune-transformed.glb [28.23KB] (95%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

function Neptune({ diameter }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/neptune-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh
        geometry={nodes.Neptune.geometry}
        material={materials["Default OBJ.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

export default Neptune;

useGLTF.preload("/models/neptune-transformed.glb");
