/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./venus.glb --transform 
Files: ./venus.glb [298.75KB] > /home/enrico/Documents/development/bounce-insights-prj/asteroid-avoider/packages/client/public/models/venus-transformed.glb [27.03KB] (91%)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAutoScale } from "@/hooks/useAutoScale";

const Venus = ({ diameter }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/venus-transformed.glb");

  useAutoScale(group, diameter);

  return (
    <group ref={group} dispose={null}>
      <mesh
        geometry={nodes.cylindrically_mapped_sphereMesh.geometry}
        material={materials["Default OBJ"]}
      />
    </group>
  );
};

export default Venus;

useGLTF.preload("/models/venus-transformed.glb");
